GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies?min_value=1
###
GET http://localhost:8082/currencies/usd
###
GET http://localhost:8082/users
Authorization: LetMeIn
###
GET http://localhost:8082/users/06750d9e-84d3-4cd1-8f89-1710213d2576
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?gender=male&age=52
###
GET http://localhost:8082/users/search?gender=female
###
GET http://localhost:8082/users/search?gender=superman
###
GET http://localhost:8082/users/search?age=52
###
GET http://localhost:8082/users/search?age=-5
Authorization: LetMeIn
###
GET http://localhost:8082/users/search
Authorization: LetMeIn
### Blogs
POST http://localhost:8082/blogs
Content-Type: application/json

{
    "title": "Travel blog on Mussorie 😊",
    "authors": [
    {
    "fullName": "Aditya Singh",
    "email": "aditya@resuminator.in",
    "twitterHandle": "@_adityamadridsta_",
    "image": "https://pbs.twimg.com/profile_images/1438358493799452672/vNWqLAHP_400x400.jpg"
    }],
    "content": "5 hidden gems of Mussorie",
    "publishedAt": null
}
###
GET http://localhost:8082/blogs
###
GET http://localhost:8082/blogs/667234585cb76bd6a39b6971
###
DELETE http://localhost:8082/blogs/6674dbb13ad83227f38a65e2
###
PATCH http://localhost:8082/blogs/667234585cb76bd6a39b6971
Content-Type: application/json

{
    "title": "Travel blog on Lake District",
    "authors": [
    {
    "fullName": "John Doe",
    "email": "john@resuminator.in",
    "twitterHandle": "@_johndoe_",
    "image": "https://pbs.twimg.com/profile_images/1438358493799452672/vNWqLAHP_400x400.jpg"
    },
    {
    "fullName": "Jane Doe",
    "email": "jane@resuminator.in",
    "twitterHandle": "@_janedoe_",
    "image": "https://pbs.twimg.com/profile_images/1438358493799452672/vNWqLAHP_400x400.jpg"
}],
    "content": "5 hidden gems of Lake district....",
    "publishedAt": null
}
###
GET http://localhost:8082/blogs/search?title=travel%20blog%20on%20Lake%20District
###
GET http://localhost:8082/blogs/search?title=travel
###
GET http://localhost:8082/blogs/search?title=😊
###
GET http://localhost:8082/blogs/search?title=district&author=john@resuminator.in
###
GET http://localhost:8082/blogs/search?author=aditya@resuminator.in
###